services:
  - type: web
    name: cp5-mobile
    env: node
    rootDir: server
    buildCommand: npm install && npx tsc
    startCommand: npm start
    envVars:
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: CRON_SECRET
        sync: false

  - type: cron
    name: push-receipts-cron
    env: node
    schedule: "*/30 * * * *"
    command: curl -X POST -H "x-cron-secret:$CRON_SECRET" https://cp5-mobile.onrender.com/notifications/receipts
    envVars:
      - key: CRON_SECRET
        sync: false
